// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace aspmvc73.Osoba
{
    public partial class Osoba
    {
        [Key]
        public int OsobaId { get; set; }

        [Required(ErrorMessage = "Unesite ime")]
        [StringLength(30, ErrorMessage = "Maksimalono 30 karaktera")]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Unesite prezime")]
        [StringLength(30, ErrorMessage = "Maksimalono 30 karaktera")]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Unesite adresu")]
        [StringLength(60, ErrorMessage = "Maksimalono 60 karaktera")]
        public string Adresa { get; set; }

       // [Column(TypeName = "date")]
        [Required(ErrorMessage = "Unesite datum rodjenja")]
        [Display(Name = "Datum rodjenja")]
        [DisplayFormat(DataFormatString = "{0:dd.mm.yyyy}",ApplyFormatInEditMode =true)]
        public DateTime DatumRodjenja { get; set; }

        [Required(ErrorMessage = "Unesite telefon")]
        [RegularExpression(@"\{3}-\d{3}-d{4}", ErrorMessage = "Telefon mora biti u formatu 000-000-0000")]
       // [StringLength(20, ErrorMessage = "Maksimalono 20 karaktera")]
        public string Telefon { get; set; }
    }
}